name: brilliantcrank
favicon: null
layout_spectrum: 0.8291688705794513
typography_spectrum: 0.050035845721140504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3333810248877853
  lightness: 0.7474090666510165
  saturation: 0.8220054015982896
  rhythmicContrast: 0.7027550591155887
purpose: []
